[run]
  timeout = "3m"

[linters-settings]

  [linters-settings.govet]

  [linters-settings.gocyclo]
    min-complexity = 12.0

  [linters-settings.goconst]
    min-len = 3.0
    min-occurrences = 4.0

  [linters-settings.misspell]
    locale = "US"

  [linters-settings.funlen]
    lines = 60 # default 60
    statements = 40 # default 40

[linters]
  enable-all = true
  disable = [
    "golint", # deprecated
    "scopelint", # deprecated
    "interfacer", # deprecated
    "maligned", # deprecated
    "cyclop",
    "bodyclose",
    "goerr113",
    "nlreturn",
    "exhaustivestruct",
    "testpackage",
    "paralleltest",
    "tparallel",
    "gomnd",
    "wrapcheck",
  ]

[issues]
  exclude-use-default = false
  max-same-issues = 0
  exclude = [
    "don't use an underscore in package name",
    "ST1003: should not use underscores in package names"
  ]

 [[issues.exclude-rules]]
    path = "(.+)_test.go"
    linters = ["goconst", "funlen", "godot", "scopelint"]
