version = '2'

[linters]
default = 'all'
disable = [
  'bodyclose',
  'cyclop',
  'err113',
  'mnd',
  'nlreturn',
  'paralleltest',
  'testpackage',
  'tparallel',
  'wrapcheck'
]

[linters.settings]
[linters.settings.funlen]
lines = 60
statements = 40

[linters.settings.goconst]
min-len = 3
min-occurrences = 4

[linters.settings.gocyclo]
min-complexity = 12

[linters.settings.misspell]
locale = 'US'

[linters.exclusions]
generated = 'lax'
paths = [
  'third_party$',
  'builtin$',
  'examples$'
]

[[linters.exclusions.rules]]
linters = [
  'funlen',
  'goconst',
  'godot',
  'scopelint'
]
path = '(.+)_test.go'

[[linters.exclusions.rules]]
path = '(.+)\.go$'
text = """
don't use an underscore in package name"""

[[linters.exclusions.rules]]
path = '(.+)\.go$'
text = 'ST1003: should not use underscores in package names'

[issues]
max-same-issues = 0

[formatters]
enable = [
  'gci',
  'gofmt',
  'gofumpt',
  'goimports'
]

[formatters.exclusions]
generated = 'lax'
paths = [
  'third_party$',
  'builtin$',
  'examples$'
]
