displayName: Simple Force Cache
summary: Simple cache plugin middleware caches responses on disk.
type: middleware
import: github.com/gfreezy/plugin-simpleforcecache
compatibility: TODO
testData:
  path: /tmp
  maxExpiry: 300
  cleanup: 600
  addStatusHeader: true
  cacheHeaders:
    - "Accept-Language"
  cachePathPrefixes:
    - "/api/"
